/**
 * SITS field catalogue — key fields per entity with HESA mapping references.
 * Not exhaustive; covers the 150+ fields required for audit rules and migration.
 */

export interface FieldCatalogueEntry {
  entityKey: string;
  fieldName: string;
  sitsColumn: string;
  sitsTable: string;
  hesaFieldRef?: string;
  dataType: "string" | "date" | "integer" | "decimal" | "boolean" | "codelist";
  isMandatory: boolean;
  codelistId?: string;
  description: string;
}

export const SITS_FIELD_CATALOGUE: FieldCatalogueEntry[] = [
  // ── Student ──────────────────────────────────────────────────────────────
  {
    entityKey: "Student",
    fieldName: "studentId",
    sitsColumn: "STU_CODE",
    sitsTable: "STU",
    dataType: "string",
    isMandatory: true,
    description: "SITS student code (primary key)",
  },
  {
    entityKey: "Student",
    fieldName: "surname",
    sitsColumn: "STU_SURN",
    sitsTable: "STU",
    hesaFieldRef: "SURNAME",
    dataType: "string",
    isMandatory: true,
    description: "Student surname",
  },
  {
    entityKey: "Student",
    fieldName: "forenames",
    sitsColumn: "STU_FORE",
    sitsTable: "STU",
    hesaFieldRef: "FNAMES",
    dataType: "string",
    isMandatory: true,
    description: "Student forenames",
  },
  {
    entityKey: "Student",
    fieldName: "dateOfBirth",
    sitsColumn: "STU_DOB",
    sitsTable: "STU",
    hesaFieldRef: "BIRTHDTE",
    dataType: "date",
    isMandatory: true,
    description: "Date of birth",
  },
  {
    entityKey: "Student",
    fieldName: "sexId",
    sitsColumn: "STU_SEX",
    sitsTable: "STU",
    hesaFieldRef: "SEXID",
    dataType: "codelist",
    codelistId: "HESA.SEXID",
    isMandatory: true,
    description: "Sex identifier",
  },
  {
    entityKey: "Student",
    fieldName: "nationalId",
    sitsColumn: "STU_NID",
    sitsTable: "STU",
    dataType: "string",
    isMandatory: false,
    description: "National identity document number",
  },
  {
    entityKey: "Student",
    fieldName: "niNumber",
    sitsColumn: "STU_NINO",
    sitsTable: "STU",
    dataType: "string",
    isMandatory: false,
    description: "National Insurance number",
  },
  {
    entityKey: "Student",
    fieldName: "husid",
    sitsColumn: "STU_HUSID",
    sitsTable: "STU",
    hesaFieldRef: "HUSID",
    dataType: "string",
    isMandatory: false,
    description: "HESA Unique Student Identifier",
  },
  {
    entityKey: "Student",
    fieldName: "tte",
    sitsColumn: "STU_TTE",
    sitsTable: "STU",
    hesaFieldRef: "TTE",
    dataType: "codelist",
    codelistId: "HESA.TTE",
    isMandatory: false,
    description: "Term-time education indicator",
  },
  // ── Enrolment ─────────────────────────────────────────────────────────────
  {
    entityKey: "Enrolment",
    fieldName: "enrolmentId",
    sitsColumn: "SRS_CODE",
    sitsTable: "SRS",
    dataType: "string",
    isMandatory: true,
    description: "SITS route code",
  },
  {
    entityKey: "Enrolment",
    fieldName: "studentId",
    sitsColumn: "SRS_STUC",
    sitsTable: "SRS",
    dataType: "string",
    isMandatory: true,
    description: "FK to Student",
  },
  {
    entityKey: "Enrolment",
    fieldName: "programmeCode",
    sitsColumn: "SRS_PROG",
    sitsTable: "SRS",
    hesaFieldRef: "COURSEAIM",
    dataType: "string",
    isMandatory: true,
    description: "Programme of study code",
  },
  {
    entityKey: "Enrolment",
    fieldName: "modeOfStudy",
    sitsColumn: "SRS_MODE",
    sitsTable: "SRS",
    hesaFieldRef: "MODE",
    dataType: "codelist",
    codelistId: "HESA.MODE",
    isMandatory: true,
    description: "Mode of study",
  },
  {
    entityKey: "Enrolment",
    fieldName: "startDate",
    sitsColumn: "SRS_BEGD",
    sitsTable: "SRS",
    hesaFieldRef: "COMDATE",
    dataType: "date",
    isMandatory: true,
    description: "Enrolment commencement date",
  },
  {
    entityKey: "Enrolment",
    fieldName: "endDate",
    sitsColumn: "SRS_ENDD",
    sitsTable: "SRS",
    hesaFieldRef: "ENDDATE",
    dataType: "date",
    isMandatory: false,
    description: "Enrolment end date",
  },
  {
    entityKey: "Enrolment",
    fieldName: "reasonForEnding",
    sitsColumn: "SRS_REND",
    sitsTable: "SRS",
    hesaFieldRef: "RSNEND",
    dataType: "codelist",
    codelistId: "HESA.RSNEND",
    isMandatory: false,
    description: "Reason for ending study",
  },
  {
    entityKey: "Enrolment",
    fieldName: "fundingBody",
    sitsColumn: "SRS_FUND",
    sitsTable: "SRS",
    hesaFieldRef: "FUNDCOMP",
    dataType: "codelist",
    codelistId: "HESA.FUNDCOMP",
    isMandatory: false,
    description: "Funding body / source",
  },
  {
    entityKey: "Enrolment",
    fieldName: "expectedEndDate",
    sitsColumn: "SRS_EXPE",
    sitsTable: "SRS",
    hesaFieldRef: "ENDDATE",
    dataType: "date",
    isMandatory: false,
    description: "Expected end date",
  },
  // ── Programme ────────────────────────────────────────────────────────────
  {
    entityKey: "Programme",
    fieldName: "programmeCode",
    sitsColumn: "POS_CODE",
    sitsTable: "POS",
    dataType: "string",
    isMandatory: true,
    description: "Programme code",
  },
  {
    entityKey: "Programme",
    fieldName: "title",
    sitsColumn: "POS_NAME",
    sitsTable: "POS",
    hesaFieldRef: "CTITLE",
    dataType: "string",
    isMandatory: true,
    description: "Programme title",
  },
  {
    entityKey: "Programme",
    fieldName: "courseAim",
    sitsColumn: "POS_CAIM",
    sitsTable: "POS",
    hesaFieldRef: "COURSEAIM",
    dataType: "codelist",
    codelistId: "HESA.COURSEAIM",
    isMandatory: true,
    description: "HESA course aim",
  },
  {
    entityKey: "Programme",
    fieldName: "jacs3",
    sitsColumn: "POS_JAC3",
    sitsTable: "POS",
    hesaFieldRef: "SBJCA",
    dataType: "string",
    isMandatory: false,
    description: "JACS3 subject coding",
  },
  {
    entityKey: "Programme",
    fieldName: "hesacos",
    sitsColumn: "POS_HCOS",
    sitsTable: "POS",
    hesaFieldRef: "HCOSTSUBJ",
    dataType: "string",
    isMandatory: false,
    description: "HECoS subject coding",
  },
  // ── Module ───────────────────────────────────────────────────────────────
  {
    entityKey: "Module",
    fieldName: "moduleCode",
    sitsColumn: "MOD_CODE",
    sitsTable: "MOD",
    dataType: "string",
    isMandatory: true,
    description: "Module code",
  },
  {
    entityKey: "Module",
    fieldName: "title",
    sitsColumn: "MOD_NAME",
    sitsTable: "MOD",
    dataType: "string",
    isMandatory: true,
    description: "Module title",
  },
  {
    entityKey: "Module",
    fieldName: "credits",
    sitsColumn: "MOD_CRDT",
    sitsTable: "MOD",
    hesaFieldRef: "CRDTPTS",
    dataType: "integer",
    isMandatory: false,
    description: "Credit points",
  },
  {
    entityKey: "Module",
    fieldName: "level",
    sitsColumn: "MOD_LEVL",
    sitsTable: "MOD",
    hesaFieldRef: "CLEVEL",
    dataType: "codelist",
    codelistId: "HESA.CLEVEL",
    isMandatory: false,
    description: "Module level",
  },
  // ── Award ─────────────────────────────────────────────────────────────────
  {
    entityKey: "Award",
    fieldName: "awardId",
    sitsColumn: "SAW_CODE",
    sitsTable: "SAW",
    dataType: "string",
    isMandatory: true,
    description: "Award record id",
  },
  {
    entityKey: "Award",
    fieldName: "studentId",
    sitsColumn: "SAW_STUC",
    sitsTable: "SAW",
    dataType: "string",
    isMandatory: true,
    description: "FK to Student",
  },
  {
    entityKey: "Award",
    fieldName: "qualificationAim",
    sitsColumn: "SAW_QAIM",
    sitsTable: "SAW",
    hesaFieldRef: "QUALENT3",
    dataType: "codelist",
    codelistId: "HESA.QUALENT3",
    isMandatory: true,
    description: "Qualification aim",
  },
  {
    entityKey: "Award",
    fieldName: "classOfAward",
    sitsColumn: "SAW_CLAW",
    sitsTable: "SAW",
    hesaFieldRef: "CLSSHONS",
    dataType: "codelist",
    codelistId: "HESA.CLSSHONS",
    isMandatory: false,
    description: "Class of honours",
  },
  {
    entityKey: "Award",
    fieldName: "dateOfAward",
    sitsColumn: "SAW_DAWD",
    sitsTable: "SAW",
    dataType: "date",
    isMandatory: false,
    description: "Date of award",
  },
];
