import type { FieldDefinition } from "@databridge/platform";

export const HESA_TDP_FIELDS: FieldDefinition[] = [
  // ── Student ──────────────────────────────────────────────────────────────
  {
    id: "HUSID",
    entity: "Student",
    label: "HESA Unique Student Identifier",
    hesaRef: "HUSID",
    type: "string",
    required: true,
    maxLength: 13,
    description: "13-digit identifier assigned by HESA. First digit = 0 for non-dormant.",
  },
  {
    id: "UKPRN",
    entity: "Student",
    label: "UK Provider Reference Number",
    hesaRef: "UKPRN",
    type: "string",
    required: true,
    maxLength: 8,
  },
  {
    id: "OWNSTU",
    entity: "Student",
    label: "Provider's own student identifier",
    hesaRef: "OWNSTU",
    type: "string",
    required: true,
    maxLength: 20,
  },
  {
    id: "SURNAME",
    entity: "Student",
    label: "Surname",
    hesaRef: "SURNAME",
    type: "string",
    required: true,
    maxLength: 40,
  },
  {
    id: "FNAMES",
    entity: "Student",
    label: "Forenames",
    hesaRef: "FNAMES",
    type: "string",
    required: true,
    maxLength: 40,
  },
  {
    id: "BIRTHDTE",
    entity: "Student",
    label: "Date of birth",
    hesaRef: "BIRTHDTE",
    type: "date",
    required: true,
  },
  {
    id: "SEXID",
    entity: "Student",
    label: "Sex identifier",
    hesaRef: "SEXID",
    type: "coded",
    required: true,
    codingFrame: "SEXID",
  },
  {
    id: "ETHNIC",
    entity: "Student",
    label: "Ethnicity",
    hesaRef: "ETHNIC",
    type: "coded",
    required: true,
    codingFrame: "ETHNIC",
  },
  {
    id: "NATION",
    entity: "Student",
    label: "Nationality",
    hesaRef: "NATION",
    type: "coded",
    required: true,
    codingFrame: "NATION",
  },
  {
    id: "DOMICILE",
    entity: "Student",
    label: "Domicile",
    hesaRef: "DOMICILE",
    type: "coded",
    required: true,
    codingFrame: "DOMICILE",
  },
  {
    id: "DISABLE",
    entity: "Student",
    label: "Disability",
    hesaRef: "DISABLE",
    type: "coded",
    required: true,
    codingFrame: "DISABLE",
    multiValue: true,
  },
  {
    id: "TERMTIME",
    entity: "Student",
    label: "Term-time accommodation",
    hesaRef: "TERMTIME",
    type: "coded",
    required: false,
    codingFrame: "TERMTIME",
  },
  // ── Engagement ───────────────────────────────────────────────────────────
  {
    id: "ENGID",
    entity: "Engagement",
    label: "Engagement identifier",
    hesaRef: "ENGID",
    type: "string",
    required: true,
    maxLength: 20,
  },
  {
    id: "AWARDBOD",
    entity: "Engagement",
    label: "Awarding body",
    hesaRef: "AWARDBOD",
    type: "coded",
    required: true,
    codingFrame: "AWARDBOD",
  },
  {
    id: "COURSEAIM",
    entity: "Engagement",
    label: "Course aim",
    hesaRef: "COURSEAIM",
    type: "coded",
    required: true,
    codingFrame: "COURSEAIM",
  },
  // ── StudentCourseSession ──────────────────────────────────────────────────
  {
    id: "COMDATE",
    entity: "StudentCourseSession",
    label: "Course commencement date",
    hesaRef: "COMDATE",
    type: "date",
    required: true,
  },
  {
    id: "ENDDATE",
    entity: "StudentCourseSession",
    label: "Expected end date",
    hesaRef: "ENDDATE",
    type: "date",
    required: false,
  },
  {
    id: "MODE",
    entity: "StudentCourseSession",
    label: "Mode of study",
    hesaRef: "MODE",
    type: "coded",
    required: true,
    codingFrame: "MODE",
  },
  {
    id: "STULOAD",
    entity: "StudentCourseSession",
    label: "Student FTE load",
    hesaRef: "STULOAD",
    type: "decimal",
    required: false,
    precision: 3,
    scale: 1,
  },
  {
    id: "FUNDLEV",
    entity: "StudentCourseSession",
    label: "Level of funding",
    hesaRef: "FUNDLEV",
    type: "coded",
    required: true,
    codingFrame: "FUNDLEV",
  },
  {
    id: "MSTUFEE",
    entity: "StudentCourseSession",
    label: "Fee regime",
    hesaRef: "MSTUFEE",
    type: "coded",
    required: true,
    codingFrame: "MSTUFEE",
  },
  {
    id: "GROSSFEE",
    entity: "StudentCourseSession",
    label: "Gross tuition fee (£)",
    hesaRef: "GROSSFEE",
    type: "integer",
    required: false,
  },
  // ── Module ────────────────────────────────────────────────────────────────
  {
    id: "MODID",
    entity: "Module",
    label: "Module identifier",
    hesaRef: "MODID",
    type: "string",
    required: true,
    maxLength: 20,
  },
  {
    id: "MODDESC",
    entity: "Module",
    label: "Module description",
    hesaRef: "MODDESC",
    type: "string",
    required: true,
    maxLength: 60,
  },
  {
    id: "CRDTPTS",
    entity: "Module",
    label: "Credit points",
    hesaRef: "CRDTPTS",
    type: "integer",
    required: false,
  },
  {
    id: "HECOS",
    entity: "Module",
    label: "HECoS subject coding",
    hesaRef: "HECOS",
    type: "coded",
    required: true,
    codingFrame: "HECOS",
    multiValue: true,
  },
  // ── Leaver ────────────────────────────────────────────────────────────────
  {
    id: "RSNEND",
    entity: "Leaver",
    label: "Reason for ending",
    hesaRef: "RSNEND",
    type: "coded",
    required: true,
    codingFrame: "RSNEND",
  },
  {
    id: "QUALSBJ",
    entity: "Leaver",
    label: "Subject of qualification awarded",
    hesaRef: "QUALSBJ",
    type: "coded",
    required: false,
    codingFrame: "HECOS",
  },
  // ── EntryProfile ──────────────────────────────────────────────────────────
  {
    id: "QUALENT3",
    entity: "EntryProfile",
    label: "Highest qualification on entry",
    hesaRef: "QUALENT3",
    type: "coded",
    required: true,
    codingFrame: "QUALENT3",
  },
  {
    id: "SCHOOLty",
    entity: "EntryProfile",
    label: "Type of school last attended",
    hesaRef: "SCHOOLTY",
    type: "coded",
    required: false,
    codingFrame: "SCHOOLTY",
  },
  {
    id: "UCASAPP",
    entity: "EntryProfile",
    label: "UCAS application number",
    hesaRef: "UCASAPP",
    type: "string",
    required: false,
    maxLength: 10,
  },
];

/** Back-compat alias used by tests (and some external consumers). */
export const HESA_FIELD_CATALOGUE = HESA_TDP_FIELDS;
