import type { CodingFrame } from "@databridge/platform";

export const ETHNIC: CodingFrame = {
  id: "ETHNIC",
  label: "Ethnicity",
  hesaRef: "ETHNIC",
  values: [
    { code: "10", label: "White" },
    { code: "11", label: "White - British" },
    { code: "12", label: "White - Irish" },
    { code: "13", label: "White - Scottish" },
    { code: "19", label: "Other White background" },
    { code: "21", label: "Black or Black British - Caribbean" },
    { code: "22", label: "Black or Black British - African" },
    { code: "29", label: "Other Black background" },
    { code: "31", label: "Asian or Asian British - Indian" },
    { code: "32", label: "Asian or Asian British - Pakistani" },
    { code: "33", label: "Asian or Asian British - Bangladeshi" },
    { code: "34", label: "Chinese" },
    { code: "39", label: "Other Asian background" },
    { code: "41", label: "Mixed - White and Black Caribbean" },
    { code: "42", label: "Mixed - White and Black African" },
    { code: "43", label: "Mixed - White and Asian" },
    { code: "49", label: "Other mixed background" },
    { code: "50", label: "Arab" },
    { code: "80", label: "Other ethnic background" },
    { code: "90", label: "Not known" },
    { code: "98", label: "Information refused" },
  ],
};
