import type { DhpDimension } from './types';

export const DHP_DIMENSIONS: DhpDimension[] = [
  'COMPLETENESS',
  'CONFORMANCE',
  'CONSISTENCY',
  'TIMELINESS',
  'UNIQUENESS',
  'REFERENTIAL_INTEGRITY',
];

/** Weights must sum to 1.0 */
export const DIMENSION_WEIGHTS: Record<DhpDimension, number> = {
  COMPLETENESS: 0.25,
  CONFORMANCE: 0.25,
  CONSISTENCY: 0.20,
  TIMELINESS: 0.10,
  UNIQUENESS: 0.10,
  REFERENTIAL_INTEGRITY: 0.10,
};

/** Rule family → DHP dimension mapping */
export const FAMILY_TO_DIMENSION: Record<string, DhpDimension> = {
  COMPLETENESS: 'COMPLETENESS',
  FORMAT: 'CONFORMANCE',
  CODING: 'CONFORMANCE',
  TEMPORAL: 'CONSISTENCY',
  CONSISTENCY: 'CONSISTENCY',
  REFERENTIAL: 'REFERENTIAL_INTEGRITY',
  UNIQUENESS: 'UNIQUENESS',
  TIMELINESS: 'TIMELINESS',
};
