/**
 * SJMS 5 (Prisma/Postgres) SourceAdapter implementation.
 *
 * - Read-only adapter for the Postgres schema generated by Prisma in Freddie's
 *   SJMS-2.5 platform.
 * - Loads the `pg` package lazily so the workspace remains installable without
 *   native Postgres tooling.
 * - All credentials flow through ctx.secrets — process.env is never read here.
 * - streamRows() uses keyset pagination on the primary key column, producing
 *   stable pages without OFFSET-induced row skew.
 * - All SQL is parameterised and table/column identifiers are sourced from
 *   the static SJMS5_RESOURCES map (allowlisted + regex-checked at quote time).
 */
import type {
  SourceAdapter,
  AdapterCapabilities,
  AdapterContext,
  HealthCheckResult,
  SampleTableArgs,
  SampledRow,
  StreamRowsArgs,
  StreamRowsPage,
  GetRecordByIdArgs,
  SchemaDescriptor,
  CodeList,
  DictionaryEntry,
} from "@databridge/adapter-spec";

import { Sjms5ConfigSchema, type Sjms5Config } from "./config.js";
import {
  SJMS5_RESOURCES,
  SJMS5_RESOURCE_NAMES,
  quoteIdent,
  type ResourceDescriptor,
} from "./resource-map.js";
import { loadPg, type PgClientLike } from "./pg-client.js";

const DEFAULT_PAGE_SIZE = 500;

/**
 * Factory that produces a connected pg client from a connection string.
 * The default factory loads the pg peer dependency lazily. Tests inject a
 * mock factory to avoid standing up Postgres.
 */
export type PgClientFactory = (
  connectionString: string,
  meta: { statementTimeoutMs: number; applicationName: string }
) => Promise<PgClientLike>;

export interface Sjms5AdapterOptions {
  /** Override the pg client factory (test-only). */
  clientFactory?: PgClientFactory;
}

const defaultClientFactory: PgClientFactory = async (connectionString, meta) => {
  const { Client } = await loadPg();
  const client = new Client({
    connectionString,
    statement_timeout: meta.statementTimeoutMs,
    application_name: meta.applicationName,
  });
  await client.connect();
  return client;
};

export class Sjms5Adapter implements SourceAdapter {
  readonly id = "sjms5";
  readonly displayName = "SJMS 5 (Prisma/Postgres)";
  readonly capabilities: AdapterCapabilities = {
    supportsIncremental: true,
    supportsDictionary: false,
    supportsSampling: true,
    supportsCodeLists: false,
    preferredAuth: "db-credentials",
    rateLimitHintRps: 0,
  };

  private readonly config: Sjms5Config;
  private readonly clientFactory: PgClientFactory;

  constructor(rawConfig: unknown, options: Sjms5AdapterOptions = {}) {
    this.config = Sjms5ConfigSchema.parse(rawConfig);
    this.clientFactory = options.clientFactory ?? defaultClientFactory;
  }

  // ---- Connection helpers ---------------------------------------------------

  private async openClient(ctx: AdapterContext): Promise<PgClientLike> {
    if (ctx.signal.aborted) {
      throw new Error("adapter-sjms5: aborted before query");
    }
    const connectionString = await ctx.secrets.get(this.config.databaseUrlSecretKey);
    const client = await this.clientFactory(connectionString, {
      statementTimeoutMs: this.config.statementTimeoutMs,
      applicationName: `databridge-sjms5/${ctx.tenantId}/${ctx.connectionId}`,
    });
    ctx.signal.addEventListener(
      "abort",
      () => {
        void client.end().catch(() => undefined);
      },
      { once: true }
    );
    return client;
  }

  private resourceOrThrow(resource: string): ResourceDescriptor {
    const desc = SJMS5_RESOURCES[resource];
    if (!desc) {
      throw new Error(
        `adapter-sjms5: resource '${resource}' not supported. ` +
          `Known: ${SJMS5_RESOURCE_NAMES.join(", ")}`
      );
    }
    return desc;
  }

  private qualified(desc: ResourceDescriptor): string {
    return `${quoteIdent(this.config.schema)}.${quoteIdent(desc.relation)}`;
  }

  private projection(desc: ResourceDescriptor): string {
    return desc.columns.map((c) => quoteIdent(c)).join(", ");
  }

  // ---- SourceAdapter contract ----------------------------------------------

  async healthCheck(ctx: AdapterContext): Promise<HealthCheckResult> {
    const start = Date.now();
    ctx.logger.debug("sjms5: healthCheck invoked");
    let client: PgClientLike | undefined;
    try {
      client = await this.openClient(ctx);
      await client.query("SELECT 1");
      return {
        healthy: true,
        latencyMs: Date.now() - start,
        message: "ok",
        details: { resources: SJMS5_RESOURCE_NAMES.length },
      };
    } catch (err) {
      return {
        healthy: false,
        latencyMs: Date.now() - start,
        message: (err as Error).message,
      };
    } finally {
      if (client) await client.end().catch(() => undefined);
    }
  }

  async discoverSchema(ctx: AdapterContext): Promise<SchemaDescriptor> {
    ctx.logger.debug("sjms5: discoverSchema invoked");
    // Use information_schema to discover live column metadata. This means new
    // columns added in SJMS5 surface automatically; we only project columns
    // declared in resource-map.ts but discoverSchema reports the union.
    const client = await this.openClient(ctx);
    try {
      const generatedAt = new Date().toISOString();
      const resources = [];
      for (const desc of Object.values(SJMS5_RESOURCES)) {
        const cols = await client.query<{
          column_name: string;
          data_type: string;
          is_nullable: string;
        }>(
          `SELECT column_name, data_type, is_nullable
             FROM information_schema.columns
            WHERE table_schema = $1 AND table_name = $2
            ORDER BY ordinal_position`,
          [this.config.schema, desc.relation]
        );
        resources.push({
          name: desc.resource,
          kind: "endpoint" as const,
          description: `${this.displayName} resource: ${desc.resource}`,
          fields: cols.rows.map((r) => ({
            name: r.column_name,
            type: mapPgType(r.data_type),
            nullable: r.is_nullable === "YES",
            isKey: r.column_name === desc.pkColumn,
          })),
        });
      }
      return { adapter: this.id, generatedAt, resources };
    } finally {
      await client.end().catch(() => undefined);
    }
  }

  async sampleTable(ctx: AdapterContext, args: SampleTableArgs): Promise<SampledRow[]> {
    ctx.logger.debug("sjms5: sampleTable", {
      resource: args.resource,
      limit: args.limit,
    });
    const desc = this.resourceOrThrow(args.resource);
    const limit = Math.min(Math.max(1, args.limit | 0), this.config.sampleDefaultLimit * 10);
    const orderBy =
      args.orderBy && /^[a-zA-Z_][a-zA-Z0-9_]*$/.test(args.orderBy) ? args.orderBy : desc.pkColumn;
    const client = await this.openClient(ctx);
    try {
      const result = await client.query<SampledRow>(
        `SELECT ${this.projection(desc)}
           FROM ${this.qualified(desc)}
          ORDER BY ${quoteIdent(orderBy)} ASC
          LIMIT $1`,
        [limit]
      );
      return result.rows.map(normalizeRow);
    } finally {
      await client.end().catch(() => undefined);
    }
  }

  async *streamRows(ctx: AdapterContext, args: StreamRowsArgs): AsyncIterable<StreamRowsPage> {
    ctx.logger.debug("sjms5: streamRows", { resource: args.resource });
    const desc = this.resourceOrThrow(args.resource);
    const pageSize = Math.min(Math.max(1, args.pageSize ?? DEFAULT_PAGE_SIZE), 10_000);
    const client = await this.openClient(ctx);

    try {
      // total count is informational; cheap enough on indexed pk.
      const totalRes = await client.query<{ c: string }>(
        `SELECT COUNT(*)::text AS c FROM ${this.qualified(desc)}`
      );
      const totalRows = Number(totalRes.rows[0]?.c ?? 0);

      // Cursor encodes the last seen pk value.
      let cursorPk: string | null = args.cursor ?? null;
      const params: unknown[] = [];
      const whereParts: string[] = [];

      // Incremental filter
      if (args.sinceTimestamp !== undefined && desc.incrementalColumn !== undefined) {
        params.push(args.sinceTimestamp);
        whereParts.push(`${quoteIdent(desc.incrementalColumn)} >= $${params.length}`);
      }

      // Keyset pagination loop
      while (!ctx.signal.aborted) {
        const localParts = [...whereParts];
        const localParams = [...params];
        if (cursorPk !== null) {
          localParams.push(cursorPk);
          localParts.push(`${quoteIdent(desc.pkColumn)} > $${localParams.length}`);
        }
        const whereSql = localParts.length ? `WHERE ${localParts.join(" AND ")}` : "";
        localParams.push(pageSize);
        const sql = `SELECT ${this.projection(desc)}
                       FROM ${this.qualified(desc)}
                       ${whereSql}
                      ORDER BY ${quoteIdent(desc.pkColumn)} ASC
                      LIMIT $${localParams.length}`;
        const res = await client.query<SampledRow>(sql, localParams);
        const rows = res.rows.map(normalizeRow);
        if (rows.length === 0) {
          yield { rows: [], totalRows };
          return;
        }
        const last = rows[rows.length - 1] as SampledRow;
        const nextCursorValue = last[desc.pkColumn];
        const nextCursor =
          nextCursorValue === null || nextCursorValue === undefined
            ? undefined
            : String(nextCursorValue);
        const page: StreamRowsPage = { rows, totalRows };
        if (nextCursor !== undefined) page.nextCursor = nextCursor;
        yield page;
        if (rows.length < pageSize) return;
        cursorPk = nextCursor ?? null;
      }
    } finally {
      await client.end().catch(() => undefined);
    }
  }

  async getCodeLists(_ctx: AdapterContext): Promise<CodeList[]> {
    // SJMS5 does not expose code lists; this adapter intentionally returns [].
    return [];
  }

  async getDictionary(_ctx: AdapterContext): Promise<DictionaryEntry[]> {
    // SJMS5 has no dictionary export.
    return [];
  }

  async getRecordById(ctx: AdapterContext, args: GetRecordByIdArgs): Promise<SampledRow | null> {
    ctx.logger.debug("sjms5: getRecordById", { resource: args.resource, id: args.id });
    const desc = this.resourceOrThrow(args.resource);
    const client = await this.openClient(ctx);
    try {
      const res = await client.query<SampledRow>(
        `SELECT ${this.projection(desc)}
           FROM ${this.qualified(desc)}
          WHERE ${quoteIdent(desc.pkColumn)} = $1
          LIMIT 1`,
        [args.id]
      );
      const row = res.rows[0];
      return row ? normalizeRow(row) : null;
    } finally {
      await client.end().catch(() => undefined);
    }
  }
}

// ---------- helpers ----------

function mapPgType(pg: string): string {
  switch (pg) {
    case "integer":
    case "bigint":
    case "smallint":
    case "numeric":
    case "double precision":
    case "real":
      return "number";
    case "boolean":
      return "boolean";
    case "timestamp with time zone":
    case "timestamp without time zone":
    case "date":
      return "datetime";
    default:
      return "string";
  }
}

function normalizeRow(row: Record<string, unknown>): SampledRow {
  const out: SampledRow = {};
  for (const [k, v] of Object.entries(row)) {
    if (v === null || v === undefined) {
      out[k] = null;
    } else if (typeof v === "string" || typeof v === "number" || typeof v === "boolean") {
      out[k] = v;
    } else if (v instanceof Date) {
      out[k] = v.toISOString();
    } else {
      // bigints, buffers, jsonb objects → stringify defensively.
      out[k] = String(v);
    }
  }
  return out;
}

export const SUPPORTED_RESOURCES = SJMS5_RESOURCE_NAMES;
export type SupportedResource = (typeof SJMS5_RESOURCE_NAMES)[number];
